#!groovy
@Library('dexma') _

jenkinsfileCiPipeline(gitRepoName: 'caixa-dashboards-front',
                      gitProjectName: 'external',
                      languageName: 'npm',
                      qualityGate: 'false',
                      showTestResults: 'false')