export const dummyData = [
	{
		ID: '1',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: false,
		Alumbrado: 0,
		Clima: 0,
		Banderola: 0,
		Rotulo: 0,
		Consumo_Clima: 0,
		Confort: 0,
		Total_Anomalías: 3,
		Impacto_Anomalías: 2,
		Detected_Score: 0,
		Ahorro_Potencial: 0
	},
	{
		ID: '2',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: false,
		Alumbrado: 0,
		Clima: 0,
		Banderola: 0,
		Rotulo: 0,
		Consumo_Clima: 0,
		Confort: 0,
		Total_Anomalías: 3,
		Impacto_Anomalías: 2,
		Detected_Score: 50,
		Ahorro_Potencial: 0
	},
	{
		ID: '2',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: false,
		Alumbrado: 0,
		Clima: 0,
		Banderola: 0,
		Rotulo: 0,
		Consumo_Clima: 0,
		Confort: 0,
		Total_Anomalías: 3,
		Impacto_Anomalías: 50,
		Detected_Score: 20,
		Ahorro_Potencial: 0
	},
	{
		ID: '2',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: false,
		Alumbrado: 0,
		Clima: 0,
		Banderola: 0,
		Rotulo: 0,
		Consumo_Clima: 0,
		Confort: 0,
		Total_Anomalías: 30,
		Impacto_Anomalías: 2,
		Detected_Score: 30,
		Ahorro_Potencial: 0
	},
	{
		ID: '2',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: false,
		Alumbrado: 0,
		Clima: 0,
		Banderola: 0,
		Rotulo: 0,
		Consumo_Clima: 0,
		Confort: 0,
		Total_Anomalías: 30,
		Impacto_Anomalías: 2,
		Detected_Score: 30,
		Ahorro_Potencial: 0
	},
	{
		ID: '2',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: false,
		Alumbrado: 0,
		Clima: 0,
		Banderola: 0,
		Rotulo: 0,
		Consumo_Clima: 0,
		Confort: 0,
		Total_Anomalías: 30,
		Impacto_Anomalías: 2,
		Detected_Score: 80,
		Ahorro_Potencial: 0
	},
	{
		ID: '2',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: false,
		Alumbrado: 0,
		Clima: 0,
		Banderola: 0,
		Rotulo: 0,
		Consumo_Clima: 0,
		Confort: 0,
		Total_Anomalías: 30,
		Impacto_Anomalías: 2,
		Detected_Score: 70,
		Ahorro_Potencial: 0
	}
];
