export const dummyData = [
	{
		ID: '1',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: false,
		Alumbrado: 0,
		Clima: 0,
		Banderola: 0,
		Rotulo: 0,
		Consumo_Clima: 0,
		Confort: 0,
		Anomalías: 3,
		Impacto_Anomalías: 2,

	},
	{
		ID: '2',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: true,
		Alumbrado: 0,
		Clima: 0,
		Banderola: 0,
		Rotulo: 0,
		Consumo_Clima: 0,
		Confort: 0,
		Anomalías: 3,
		Impacto_Anomalías: 2,

	},
	{
		ID: '3',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: true,
		Alumbrado: 0,
		Clima: 0,
		Banderola: 0,
		Rótulo: 0,
		Consumo_Clima: 0,
		Confort: 0,
		Anomalías: 3,
		Impacto_Anomalías: 2,

	},
	{
		ID: '4',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: false,
		Alumbrado: 0,
		Clima: 0,
		Banderola: 0,
		Rótulo: 0,
		Consumo_Clima: 0,
		Confort: 0,
		Anomalías: 3,
		Impacto_Anomalías: 2,

	},
	{
		ID: '5',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: 0,
		Alumbrado: 0,
		Clima: 0,
		Banderola: 0,
		Rótulo: 0,
		Consumo_Clima: true,
		Confort: 0,
		Anomalías: 3,
		Impacto_Anomalías: 2,

	},
	{
		ID: '6',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: 0,
		Alumbrado: 0,
		Clima: 0,
		Banderola: 0,
		Rótulo: 0,
		Consumo_Clima: true,
		Confort: 0,
		Anomalías: 3,
		Impacto_Anomalías: 2,


	},
	{
		ID: '7',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: false,
		Alumbrado: false,
		Clima: false,
		Banderola: false,
		Rótulo: false,
		Consumo_Clima: false,
		Confort: 0,
		Anomalías: 3,
		Impacto_Anomalías: 2,

	},
	{
		ID: '8',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: true,
		Alumbrado: true,
		Clima: true,
		Banderola: true,
		Rótulo: true,
		Consumo_Clima: false,
		Confort: 0,
		Anomalías: 3,
		Impacto_Anomalías: 2,

	},
	{
		ID: '9',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: true,
		Alumbrado: 0,
		Clima: 0,
		Banderola: true,
		Rótulo: true,
		Consumo_Clima: false,
		Confort: 0,
		Anomalías: 3,
		Impacto_Anomalías: 2,

	},
	{
		ID: '9',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: true,
		Alumbrado: 0,
		Clima: 0,
		Banderola: true,
		Rótulo: true,
		Consumo_Clima: false,
		Confort: 0,
		Anomalías: 3,
		Impacto_Anomalías: 2,

	},
	{
		ID: '9',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: true,
		Alumbrado: 0,
		Clima: 0,
		Banderola: true,
		Rótulo: true,
		Consumo_Clima: false,
		Confort: 0,
		Anomalías: 3,
		Impacto_Anomalías: 2,

	},
	{
		ID: '9',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: true,
		Alumbrado: 0,
		Clima: 0,
		Banderola: true,
		Rótulo: true,
		Consumo_Clima: false,
		Confort: 0,
		Anomalías: 3,
		Impacto_Anomalías: 2,

	},
	{
		ID: '9',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: true,
		Alumbrado: 0,
		Clima: 0,
		Banderola: true,
		Rótulo: true,
		Consumo_Clima: false,
		Confort: 0,
		Anomalías: 3,
		Impacto_Anomalías: 2,

	},
	{
		ID: '9',
		Ciudad: 'Barcelona',
		Tipologia: 'simple',
		Comunicacion: 0,
		Pasarela_Clima: true,
		Alumbrado: 0,
		Clima: 0,
		Banderola: true,
		Rótulo: true,
		Consumo_Clima: false,
		Confort: 0,
		Anomalías: 3,
		Impacto_Anomalías: 2,

	}
];
