export const dummyData = [
  {
    ID: "1234",
    Ciudad: "Barcelona",
    Tipologia: "simple",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: "",
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: 3,
    Impacto_Anomalías: 2,
    Detected_Score: 100,
    Ahorro_Potencial: 231,
  },
  {
    ID: "1234",
    Ciudad: "Barcelona",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: "",
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: 3,
    Impacto_Anomalías: 2,
    Detected_Score: 100,
    Ahorro_Potencial: 231,
  },
  {
    ID: "1234",
    Ciudad: "Pamplona",
    Tipologia: "simple",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: "",
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: 3,
    Impacto_Anomalías: 2,
    Detected_Score: 100,
    Ahorro_Potencial: 233,
  },
  {
    ID: "1234",
    Ciudad: "rusia",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: true,
    Alumbrado: "",
    Clima: "",
    Banderola: true,
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: 3,
    Impacto_Anomalías: 2,
    Detected_Score: 100,
    Ahorro_Potencial: 232,
  },
  {
    ID: "1234",
    Ciudad: "Barcelona",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: "",
    Clima: "",
    Banderola: false,
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: 3,
    Impacto_Anomalías: 2,
    Detected_Score: 100,
    Ahorro_Potencial: 238,
  },
  {
    ID: "1234",
    Ciudad: "Barcelona",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: true,
    Alumbrado: "",
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: true,
    Confort: "",
    Anomalías: 3,
    Impacto_Anomalías: 2,
    Detected_Score: 100,
    Ahorro_Potencial: 237,
  },
  {
    ID: "1234",
    Ciudad: "Barcelona",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: "",
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: 3,
    Impacto_Anomalías: 2,
    Detected_Score: 100,
    Ahorro_Potencial: 236,
  },
  {
    ID: "1234",
    Ciudad: "Barcelona",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: "",
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: 3,
    Impacto_Anomalías: 2,
    Detected_Score: 100,
    Ahorro_Potencial: 231,
  },
  {
    ID: "1234",
    Ciudad: "Barcelona",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: "",
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: 3,
    Impacto_Anomalías: 2,
    Detected_Score: 100,
    Ahorro_Potencial: 231,
  },
  {
    ID: "1234",
    Ciudad: "Barcelona",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: "",
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: 3,
    Impacto_Anomalías: 2,
    Detected_Score: 100,
    Ahorro_Potencial: 231,
  },
  {
    ID: "1234",
    Ciudad: "Barcelona",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: "",
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: 3,
    Impacto_Anomalías: 2,
    Detected_Score: 100,
    Ahorro_Potencial: 231,
  },
  {
    ID: "2345",
    Ciudad: "Barcelona",
    Tipologia: "Simple",
    Comunicacion: "",
    Pasarela_Clima: "",
    Alumbrado: "",
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: 3,
    Impacto_Anomalías: 2,
    Detected_Score: 60,
    Ahorro_Potencial: 231,
  },
  {
    ID: "4567",
    Ciudad: "Barcelona",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: true,
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: "",
    Impacto_Anomalías: 2,
    Detected_Score: 65,
    Ahorro_Potencial: 231,
  },
  {
    ID: "4567",
    Ciudad: "Barcelona",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: true,
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: "",
    Impacto_Anomalías: 2,
    Detected_Score: 70,
    Ahorro_Potencial: 231,
  },
  {
    ID: "4567",
    Ciudad: "Barcelona",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: true,
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: "",
    Impacto_Anomalías: 2,
    Detected_Score: 75,
    Ahorro_Potencial: 231,
  },
  {
    ID: "4567",
    Ciudad: "Barcelona",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: true,
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: "",
    Impacto_Anomalías: 2,
    Detected_Score: 80,
    Ahorro_Potencial: 231,
  },
  {
    ID: "4567",
    Ciudad: "Barcelona",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: true,
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: "",
    Impacto_Anomalías: 2,
    Detected_Score: 85,
    Ahorro_Potencial: 231,
  },
  {
    ID: "4567",
    Ciudad: "Barcelona",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: true,
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: "",
    Impacto_Anomalías: 2,
    Detected_Score: 90,
    Ahorro_Potencial: 231,
  },
  {
    ID: "4567",
    Ciudad: "Barcelona",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: true,
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: "",
    Impacto_Anomalías: 2,
    Detected_Score: 95,
    Ahorro_Potencial: 231,
  },
  {
    ID: "4567",
    Ciudad: "Barcelona",
    Tipologia: "Completa",
    Comunicacion: "",
    Pasarela_Clima: false,
    Alumbrado: true,
    Clima: "",
    Banderola: "",
    Rotulo: "",
    Consumo_Clima: "",
    Confort: "",
    Anomalías: "",
    Impacto_Anomalías: 2,
    Detected_Score: 100,
    Ahorro_Potencial: 231,
  },
]