export const info = [
  {
    dot: "yellow-43",
    id: 127,
    tipo: "completa",
    ciudad: "Madrid",
    index: "Prueba",
    name: "Casal gent gran barri de la carrera",
    color: "#F25A5A",
  },
  {
    dot: "rojo-16",
    id: 245,
    tipo: "simple",
    ciudad: "Sevilla",
    index: "Prueba",
    name: "Casal gent gran barri de la carrera",
    color: "#00CC87",
  },
  {
    dot: "rojo-13",
    id: 356,
    tipo: "simple",
    ciudad: "Barcelona",
    index: "Prueba",
    name: "CAP Puif Roig",
    color: "#F25A5A",
  },
  {
    dot: "medio-green3",
    id: 465,
    tipo: "completa",
    ciudad: "Sevilla",
    index: "Prueba",
    name: "CAP Roda de Ter",
    color: "#F25A5A",
  },
  {
    dot: "light-green",
    id: 5,
    tipo: "completa",
    ciudad: "Barcelona",
    index: "Prueba",
    name: "CAP St Viçenc",
    color: "#F25A5A",
  },
  {
    dot: "rojo-10",
    id: 654,
    tipo: "completa",
    ciudad: "Madrid",
    index: "Prueba",
    name: "OT Berga",
    color: "#00CC87"
  },
  {
    dot: "yellow",
    id: 745,
    tipo: "completa",
    ciudad: "Madrid",
    index: "Prueba",
    name: "Escola Quatre Vents",
    color: "#00CC87"
  },
  {
    dot: "yellow-green",
    id: 845,
    tipo: "completa",
    ciudad: "Barcelona",
    index: "Prueba",
    name: "Escola Itaca",
    color: "#00CC87"
  },
  {
    id: 842,
    dot: "medio-green2",
    tipo: "completa",
    ciudad: "Madrid",
    index: "Prueba",
    name: "Escola Itaca",
    color: "#00CC87"
  },
  {
    id: 842,
    dot: "medio-green",
    tipo: "simple",
    ciudad: "Sevilla",
    index: "Prueba",
    name: "Escola Itaca",
    color: "#00CC87",
  },
  {
    id: 842,
    dot: "dark-green",
    tipo: "simple",
    ciudad: "Sevilla",
    index: "Prueba",
    name: "Escola Itaca",
    color: "#F25A5A",
  },
];
export const index = [
  { id: 1, name: "ID" },
  {
    name: "Ciudad",
  },
  {
    name: "Tipología",
  },
  {
    name: "Comunicación",
  },
  {
    name: "Pasarela clima",
  },
  {
    name: "Alumbrado",
  },
  {
    name: "Clima",
  },
  {
    name: "Banderola",
  },
  {
    name: "Rótulo",
  },
  {
    name: "Consumo Clima",
  },
  // CONFORT
  {
    name: "Confort",
  },
  {
    name: "#Anomalias",
  },
  {
    name: "Impacto anomalias",
  },
  {
    name: "Detected score",
  },
  {
    name: "Ahorro Potencial",
  },
];

export const info2 = [
  {
    id: 137,
    number: 14,
    number2: 53,
    number3: 81,
    number4: 9,
    tipo: "completa",
    ciudad: "Madrid",
    index: "Prueba",
    name: "Total Incidencias",
    color: "#F25A5A",
  },
  {
    id: 147,
    number: 14,
    number2: 54,
    number3: 8,
    number4: 9,
    tipo: "completa",
    ciudad: "Madrid",
    index: "Prueba",
    name: "Total Stores",
    color: "#F25A5A",
  },
  {
    dot: "rojo-vertical",
    dot1: "rojo-claro-inferior",
    dot2: "rojo-inferior",
    dot3: "rojo-medio-inferior",
    dot4: "dark-green",
    dot5: "light-green",
    dot6: "green",
    dot7: "orange",
    id: 227,
    number: '%14',
    number2: 36,
    number3: 8,
    number4: 1,
    tipo: "completa",
    ciudad: "Madrid",
    index: "Prueba",
    name: "% Incidencias",
    color: "#F25A5A",
  },
];

export const info3 = [
  {
      "id": "127",
      "ciudad": "Madrid",
      "Tipologia": "Completa",
      "Comunicacion": "true",
      "PasarelaClima": "false",
      "Alumbrado": "true",
      "Clima": "true",
      "Banderola": "true",
      "Rotulos": "false",
      "ConsumoClima": "false",
      "Confort": "red",
      "# Anomalias": 3,
      "Inpacto Anomalias": "627€",
      "Detect Score": 43,
      "Ahorro potencial": "1,528€"
  },
  {
      "id": "127",
      "ciudad": "Sevilla",
      "Tipologia": "Simple",
      "Comunicacion": "true",
      "PasarelaClima": "-",
      "Alumbrado": "true",
      "Clima": "false",
      "Banderola": "true",
      "Rotulos": "false",
      "ConsumoClima": "false",
      "Confort": "-",
      "# Anomalias": 20,
      "Inpacto Anomalias": "534€",
      "Detect Score": 16,
      "Ahorro potencial": "1,528€"
  },
  {
      "id": "127",
      "ciudad": "Barcelona",
      "Tipologia": "Simple",
      "Comunicacion": "false",
      "PasarelaClima": "-",
      "Alumbrado": "false",
      "Clima": "true",
      "Banderola": "false",
      "Rotulos": "true",
      "ConsumoClima": "true",
      "Confort": "-",
      "# Anomalias": 554,
      "Inpacto Anomalias": "536",
      "Detect Score": 13,
      "Ahorro potencial": "536€"
  },
  {
      "id": "127",
      "ciudad": "Sevilla",
      "Tipologia": "Completa",
      "Comunicacion": "true",
      "PasarelaClima": "false",
      "Alumbrado": "true",
      "Clima": "false",
      "Banderola": "true",
      "Rotulos": "false",
      "ConsumoClima": "false",
      "Confort": "false",
      "# Anomalias": 3,
      "Inpacto Anomalias": "627€",
      "Detect Score": 43,
      "Ahorro potencial": "1,528€"
  },
  {
      "id": "127",
      "ciudad": "Barcelona",
      "Tipologia": "Completa",
      "Comunicacion": "true",
      "PasarelaClima": "false",
      "Alumbrado": "true",
      "Clima": "false",
      "Banderola": "true",
      "Rotulos": "false",
      "ConsumoClima": "false",
      "Confort": "false",
      "# Anomalias": 20,
      "Inpacto Anomalias": "536€",
      "Detect Score": 76,
      "Ahorro potencial": "2017€"
  },
  {
      "id": "127",
      "ciudad": "Madrid",
      "Tipologia": "Completa",
      "Comunicacion": "true",
      "PasarelaClima": "false",
      "Alumbrado": "true",
      "Clima": "false",
      "Banderola": "true",
      "Rotulos": "false",
      "ConsumoClima": "false",
      "Confort": "false",
      "# Anomalias": 554,
      "Inpacto Anomalias": "2017€",
      "Detect Score": 10,
      "Ahorro potencial": "1946€"
  },
  {
      "id": "127",
      "ciudad": "Madrid",
      "Tipologia": "Completa",
      "Comunicacion": "true",
      "PasarelaClima": "false",
      "Alumbrado": "true",
      "Clima": "false",
      "Banderola": "true",
      "Rotulos": "false",
      "ConsumoClima": "false",
      "Confort": "false",
      "# Anomalias": 3,
      "Inpacto Anomalias": "1528€",
      "Detect Score": 55,
      "Ahorro potencial": "1,528€"
  },
  {
      "id": "127",
      "ciudad": "Barcelona",
      "Tipologia": "Completa",
      "Comunicacion": "true",
      "PasarelaClima": "true",
      "Alumbrado": "true",
      "Clima": "false",
      "Banderola": "true",
      "Rotulos": "true",
      "ConsumoClima": "true",
      "Confort": "true",
      "# Anomalias": 20,
      "Inpacto Anomalias": "536€",
      "Detect Score": 63,
      "Ahorro potencial": "727€"
  },
  {
      "id": "127",
      "ciudad": "Madrid",
      "Tipologia": "Completa",
      "Comunicacion": "true",
      "PasarelaClima": "true",
      "Alumbrado": "true",
      "Clima": "true",
      "Banderola": "true",
      "Rotulos": "false",
      "ConsumoClima": "false",
      "Confort": "false",
      "# Anomalias": 554,
      "Inpacto Anomalias": "1528€",
      "Detect Score": 79,
      "Ahorro potencial": "627€"
  },
  {
      "id": "127",
      "ciudad": "Sevilla",
      "Tipologia": "Simple",
      "Comunicacion": "true",
      "PasarelaClima": "-",
      "Alumbrado": "true",
      "Clima": "true",
      "Banderola": "true",
      "Rotulos": "true",
      "ConsumoClima": "-",
      "Confort": "-",
      "# Anomalias": 3,
      "Inpacto Anomalias": "1528€",
      "Detect Score": 55,
      "Ahorro potencial": "546€"
  },
  {
      "id": "127",
      "ciudad": "Sevilla",
      "Tipologia": "Simple",
      "Comunicacion": "false",
      "PasarelaClima": "-",
      "Alumbrado": "false",
      "Clima": "true",
      "Banderola": "false",
      "Rotulos": "false",
      "ConsumoClima": "false",
      "Confort": "-",
      "# Anomalias": 3,
      "Inpacto Anomalias": "546€",
      "Detect Score": 85,
      "Ahorro potencial": "536€"
  }
]
